gitignore-import-and-ignore: true
ignore-tree-and-content:
  - "poetry.lock"
  - "*.lock"
  - "*.json"
  - "*.toml"
  - "*.yaml"
  - "*.yml"
  - "*.md"
  - "*.txt"
  - "*.log"
  - "*.cache"
  - "*.bin"
  - "*.exe"
  - "*.dll"
  - "*.so"
  - "*.dylib"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - "__pycache__/"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.bmp"
  - "*.svg"
  - "*.ico"
  - "*.mp3"
  - "*.wav"
  - "*.mp4"
  - "*.avi"
  - "*.mkv"
  - "*.mov"
  - "*.zip"
  - "*.tar"
  - "*.gz"
  - "*.bz2"
  - "*.7z"
  - "node_modules/"
  - "venv/"
  - "env/"
  - ".venv/"
  - ".env/"
  - "build/"
  - "dist/"
  - "target/"
  - ".git/"
  - ".idea/"
  - ".vscode/"
