version: '3.8'

services:
  data_curation:
    image: ${IMAGE_DATA_CURATION}
    build:
      context: .
      dockerfile: iac/docker/Dockerfile.data_curation
    ports:
      - "8001:8001"
    volumes:
      - shared-data:/app/data/assets
    env_file:
      - .env
    restart: unless-stopped

  training:
    image: ${IMAGE_TRAINING}
    build:
      context: .
      dockerfile: iac/docker/Dockerfile.training
    ports:
      - "8002:8002"
    volumes:
      - shared-data:/app/data/datasets
      - shared-data:/app/data/whisper_finetuned
    env_file:
      - .env
    restart: unless-stopped

  serving:
    image: ${IMAGE_SERVING}
    build:
      context: .
      dockerfile: iac/docker/Dockerfile.serving
    ports:
      - "8003:8003"
    volumes:
      - shared-data:/app/data/whisper_finetuned
    env_file:
      - .env
    restart: unless-stopped

volumes:
  shared-data: