apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: whisper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs 