FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install poetry && poetry install --no-dev

COPY ./apps/serving ./apps/serving
COPY ./shared ./shared

EXPOSE 8003
CMD ["poetry", "run", "uvicorn", "apps.serving.main:app", "--host", "0.0.0.0", "--port", "8003"]
