FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install poetry && poetry install --no-dev

COPY ./apps/training ./apps/training
COPY ./shared ./shared

EXPOSE 8002
CMD ["poetry", "run", "uvicorn", "apps.training.main:app", "--host", "0.0.0.0", "--port", "8002"]
