apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  # Values should be base64 encoded
  # Example: echo -n "your-api-key" | base64
  GOOGLE_API_KEY: base64_encoded_api_key_here 