name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTAINER_REGISTRY: ghcr.io          # Non-sensitive, defined here
  REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}  # Sensitive, sourced from secrets
      GHCR_PAT: ${{ secrets.GHCR_PAT }}            # Sensitive, sourced from secrets
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_PAT }}

      # Build and push Docker images with repository name included
      - name: Build and Push Data Curation API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: iac/docker/Dockerfile.data_curation
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/data-curation:${{ github.sha }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/data-curation:latest

      - name: Docker Prune (optional)
        run: docker system prune --all --force

      - name: Build and Push Training API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: iac/docker/Dockerfile.training
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/training:${{ github.sha }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/training:latest

      - name: Docker Prune (optional)
        run: docker system prune --all --force

      - name: Build and Push Serving API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: iac/docker/Dockerfile.serving
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/serving:${{ github.sha }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ github.event.repository.name }}/serving:latest

      - name: Docker Prune (optional)
        run: docker system prune --all --force